Add documentation
datamindedbe/lighthouse pull request #5
Opened 2018-03-01 16:54 UTC by peeterskris

First iteration on tutorial, just defining a single data source in the data lake.

2018-03-07 09:35 UTC, mlavaert requested changes

2018-03-07 09:35 UTC, mlavaert commented on docs/tutorial.md
> +libraryDependencies += "be.dataminded" % "lighthouse_2.11" % "0.2.0"
`"be.dataminded" % "lighthouse" %% "0.2.0"`

2018-03-07 09:35 UTC, mlavaert commented on docs/tutorial.md
> +libraryDependencies += "be.dataminded" % "lighthouse_2.11" % "0.2.0"
Maybe also add the testing library?  `"be.dataminded" % "lighthouse-testing" %% "0.2.0" % Test`

2018-03-07 09:35 UTC, mlavaert commented on docs/tutorial.md
> +Start by adding the Lighthouse dependency to your project. In case you are using maven:
Maven

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +libraryDependencies += "be.dataminded" % "lighthouse_2.11" % "0.2.0"
use "be.dataminded" %% "lighthouse" % "0.2.0" As spark only supports scala 2.11 atm this should be fine. We should add different versions of lighthouse once spark supports multiple scala versions

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +A data lake is a collection of different data sources that we bring together in one place. Building a data lake in Lighthouse means writing Scala code. This has several advantages over more tradtiona
Configuring your data lake?

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> + 3. **Environment**: Your local development environment will (hopefully) look different from your production environment. In Lighthouse, you can define several environments and add a `DataLink` to on
Maybe also mention the test environment explicitly to run/test/debug jobs locally on your machine

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +Let's begin with defining some of those data sources. The biggest one is the airplane data itself. For this simple tutorial we define a `FileSystemDataLink` to the folder where we stored the file loc
Maybe explain the airplane use case first, before immediately jumping in? As a casual reader I have no idea why you are mentioning airplanes here ;)

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +This is telling Lighthouse: You will find a csv file in the folder `data/airplane`. The csv file has headers. You can infer the schema yourself. Now, we need to have a unique way to refer to this `Da
Maybe mention that these are spark read options and place a reference to the available configuration options?

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +val datalink = new FileSystemDataLink(
What lighthouse imports are you using here?

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +  resource("data/airplane"),
What is resource?

2018-03-07 11:34 UTC, kristofmartens commented on docs/index.md
> +Lighthouse is an open-source project to build and manage data lakes. Lighthouse is built on top of Scala and Spark. Using lighthouse, you can define the data sources available in your data lake and e
Maybe add the benefits of using lighthouse here as well. As it is not fully clear why a user would want to use lighthouse

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +    val df = AirplaneDatalake("raw" -> "airplane").read()
Maybe mention the DataUID version as well as this shows that there is a direct link between the DataUID and the data

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +This allows you to define all the data sources in your data lake in one single location, and you can use them wherever you need them. You don't need to worry about which format it's in, the exact del
Should also be available in the tldr; section/introduction of this tutorial?

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +This allows you to define all the data sources in your data lake in one single location, and you can use them wherever you need them. You don't need to worry about which format it's in, the exact del
Sentence starting with And, and 4 comma's. Split up in separate sentences

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +Having a lot of data in your data lake is only valuable once you start doing things with it. This usually involves building some sort of pipeline. There's nothing wrong with simply calling a bunch of
Remove And

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +However, in larger projects, this can quickly result in very long, hard to understand, hard to test, and hard to reuse pipelines. So how can we improve on this? By using the `Pipeline` library availa
However, in larger projects this (remove comma)
hard to test and (remove comma)
how can we improve this (remove on)

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +val airlines: SparkFunction[DataFrame] =
Maybe also provide dataset based example? Thought you were a dataset fan ;)

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +```scala
Personally note: I find it confusing that you define your DataUID with 2 strings, but use it as a Map everywhere else.
Please ignore if you don't agree

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +We'll add cleaning steps for the other two data sources, as such:
remove as such

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +Of course, we also add the two cleaned data sources to the data lake:
Why of course? Don't assume the reader knows

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +The actual implementation of the cleaning functions, you can find in the code base of Lighthouse, and don't really matter for this demo. What is cool, however, is that now we can reuse those clean da
What is cool however, (remove first comma)

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +You can find the full source code of this example in the `lighthouse-demo` folder of the Lighthouse repository. Unit tests are available to show how each aspect is supposed to work, on your own machi
Add link?

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +Note that, this time, we made it a `HiveDataLink` and we store it in the table `airplane_view` of the database `default`. That means that any consumer downstream, such as a data science process that
Note that at this time, (remove comma)

2018-03-07 11:34 UTC, kristofmartens commented on docs/tutorial.md
> +For that to work, we need to add the `master -> view` object to the data lake definition:
For this to work

2018-03-07 21:54 UTC, peeterskris commented on docs/tutorial.md
> +libraryDependencies += "be.dataminded" % "lighthouse_2.11" % "0.2.0"
The Test library is not needed for this tutorial. Maybe for the advanced.

2018-03-08 13:01 UTC, mlavaert approved these changes

2018-03-09 11:19 UTC, merged